### ISSUE TITLE
Comprobar alarma en segundo plano

### ISSUE THREAD

**Issue by damiannogueiras** [danimartinezsaa/Contornos-reloj#1]
https://github.com/danimartinezsaa/Contornos-reloj/blob/98d971f330a325affa5ba078290236c2963075af/src/contornosreloj/ContornosReloj.java#L33

Podrías comprobar la alarma en segundo plano en vez de en un bucle infinito

**Comment by danimartinezsaa** [comment]
Listo

**Comment by danimartinezsaa** [comment]
Listo
