### ISSUE TITLE
Cambiar lugar de la comprobación

### ISSUE THREAD

**Issue by damiannogueiras** [danimartinezsaa/Contornos-reloj#2]
https://github.com/danimartinezsaa/Contornos-reloj/blob/98d971f330a325affa5ba078290236c2963075af/src/contornosreloj/ContornosReloj.java#L28-L31

¿Dónde se podría hacer esta comprobación sin ser en el bucle infinito? ¿En el evento del botón?

**Comment by danimartinezsaa** [comment]
Listo
